services:
  - type: web
    name: blog-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python-3.11.9  # ✅ this line forces correct Python version
    envVars:
      - key: OPENAI_API_KEY
      - key: POSTHOG_API_KEY
      - key: POSTHOG_HOST
      - key: SECRET_KEY
